### ISSUE TITLE
DeleteCollectionsTask no longer works in ml-gradle 4.0.1

### ISSUE THREAD

**Issue by bradmann** [marklogic-community/ml-gradle#544]
Tasks of type com.marklogic.gradle.task.datamovement.DeleteCollectionsTask no longer work in ml-gradle 4.0.1

**Steps to Reproduce**
task myCollectionDeletionTask (type: com.marklogic.gradle.task.datamovement.DeleteCollectionsTask) {
    client = mlAppConfig.newDatabaseClient()
    collections = ["collectionToDelete"]
}

**Expected behavior**
Collection is deleted

**Actual behavior**
Execution failed for task ':myCollectionDeletionTask'.

**Stacktrace**
Caused by: java.lang.NoSuchMethodError: 'com.marklogic.client.query.StructuredQueryBuilder$CollectionQuery com.marklogic.client.query.StructuredQueryBuilder.collection(java.lang.String[])'

**Comment by bradmann** [comment]
Stacktrace give the following message:
Caused by: java.lang.NoSuchMethodError: 'com.marklogic.client.query.StructuredQueryBuilder$CollectionQuery com.marklogic.client.query.StructuredQueryBuilder.collection(java.lang.String[])'

**Comment by rjrudin** [comment]
Thanks, may be due to marklogic-data-movement-components still depending on Java 8 and ML Java Client 4. The NoSuchMethodError doesn't make much sense, as ML Java Client 4 and 5 have the same signature for that "collection" method. Not sure what's up yet.

**Comment by rjrudin** [comment]
Verified that when marklogic-data-movement-components is built using Java Client 5, the problem goes away.
